//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.MVC.RssParser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RssParser.IRssParser")]
    public interface IRssParser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssParser/ParseFromPage", ReplyAction="http://tempuri.org/IRssParser/ParseFromPageResponse")]
        Case.ORM.RssPage[] ParseFromPage(string _uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssParser/ParseFromPage", ReplyAction="http://tempuri.org/IRssParser/ParseFromPageResponse")]
        System.Threading.Tasks.Task<Case.ORM.RssPage[]> ParseFromPageAsync(string _uri);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRssParserChannel : Case.MVC.RssParser.IRssParser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RssParserClient : System.ServiceModel.ClientBase<Case.MVC.RssParser.IRssParser>, Case.MVC.RssParser.IRssParser {
        
        public RssParserClient() {
        }
        
        public RssParserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RssParserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssParserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssParserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Case.ORM.RssPage[] ParseFromPage(string _uri) {
            return base.Channel.ParseFromPage(_uri);
        }
        
        public System.Threading.Tasks.Task<Case.ORM.RssPage[]> ParseFromPageAsync(string _uri) {
            return base.Channel.ParseFromPageAsync(_uri);
        }
    }
}
